export const TOKENS = {
  AutoImportDipUseCase: Symbol('AutoImportDipUseCase'),
  GetDipContentUseCase: Symbol('GetDipContentUseCase'),
  GetDocumentDetailsUseCase: Symbol('GetDocumentDetailsUseCase'),
  FileFinder: Symbol('FileFinder'),
  HashService: Symbol('HashService'),
  DipParser: Symbol('DipParser'),
  DipIndexParser: Symbol('DipIndexParser'),
  AipInfoParser: Symbol('AipInfoParser'),
  MetadataParser: Symbol('MetadataParser'),
  DipRepository: Symbol('DipRepository'),
  DocumentClassRepository: Symbol('DocumentClassRepository'),
  ConservationProcessRepository: Symbol('ConservationProcessRepository'),
  DocumentRepository: Symbol('DocumentRepository'),
  DatabaseProvider: Symbol('DatabaseProvider'),
  AppConfig: Symbol('AppConfig'),
} as const;
