export const TOKENS = {
  AutoImportDipUseCase: Symbol('AutoImportDipUseCase'),
  GetDipContentUseCase: Symbol('GetDipContentUseCase'),
  CheckDipIntegrityUseCase: Symbol('CheckDipIntegrityUseCase'),
  GetDocumentDetailsUseCase: Symbol('GetDocumentDetailsUseCase'),
  DipMapper: Symbol('DipMapper'),
  DocumentClassMapper: Symbol('DocumentClassMapper'),
  ConservationProcessMapper: Symbol('ConservationProcessMapper'),
  DocumentMapper: Symbol('DocumentMapper'),
  SubjectMapper: Symbol('SubjectMapper'),
  MetadataFlattener: Symbol('MetadataFlattener'),
  FileSystemProvider: Symbol('FileSystemProvider'),
  Base64Provider: Symbol('Base64Provider'),
  HashProvider: Symbol('HashProvider'),
  DipParser: Symbol('DipParser'),
  DipIndexParser: Symbol('DipIndexParser'),
  AipInfoParser: Symbol('AipInfoParser'),
  MetadataParser: Symbol('MetadataParser'),
  DipRepository: Symbol('DipRepository'),
  DocumentClassRepository: Symbol('DocumentClassRepository'),
  ConservationProcessRepository: Symbol('ConservationProcessRepository'),
  DocumentRepository: Symbol('DocumentRepository'),
  DatabaseProvider: Symbol('DatabaseProvider'),
  AppConfig: Symbol('AppConfig'),
} as const;
