export const TOKENS = {
  AutoImportDipUseCase: Symbol('AutoImportDipUseCase'),
  GetDipContentUseCase: Symbol('GetDipContentUseCase'),
  CheckDipIntegrityUseCase: Symbol('CheckDipIntegrityUseCase'),
  GetDocumentDetailsUseCase: Symbol('GetDocumentDetailsUseCase'),
  FileSystemProvider: Symbol('FileSystemProvider'),
  Base64Provider: Symbol('Base64Provider'),
  HashProvider: Symbol('HashProvider'),
  DipParser: Symbol('DipParser'),
  DipIndexParser: Symbol('DipIndexParser'),
  AipInfoParser: Symbol('AipInfoParser'),
  MetadataParser: Symbol('MetadataParser'),
  DipRepository: Symbol('DipRepository'),
  DocumentClassRepository: Symbol('DocumentClassRepository'),
  ConservationProcessRepository: Symbol('ConservationProcessRepository'),
  DocumentRepository: Symbol('DocumentRepository'),
  DatabaseProvider: Symbol('DatabaseProvider'),
  AppConfig: Symbol('AppConfig'),
} as const;
